// Tution Media — mock data for the tutor prototype.

const TM_DATA = {
  tutor: {
    name: 'Tanvir Hasan',
    handle: '@tanvir.h',
    institution: 'BUET',
    department: 'Mechanical Engineering',
    year: '3rd year',
    cgpa: 3.78,
    verifyTier: 2,
    rating: 4.9,
    completedHires: 14,
    monthsTaught: 22,
    onTime: 98,
    retention: 86,
    earnings: 28400,
  },
  areas: ['Dhanmondi', 'Mohammadpur', 'Lalmatia'],
  subjects: ['Physics', 'Math', 'Higher Math', 'Chemistry'],
  jobs: [
    {
      id: 'j-114',
      area: 'Dhanmondi 27',
      distanceKm: 1.4,
      level: 'HSC',
      curriculum: 'National',
      subjects: ['Physics', 'Higher Math'],
      pay: 12000, payUnit: 'mo',
      days: '4 days/wk · 1.5 hr',
      window: 'Evenings · 6–9pm',
      gender: 'Any',
      posted: '8 min ago',
      match: 94,
      applicants: 3,
      guardian: { name: 'Mr. Rahman', verified: true },
      note: 'Daughter is preparing for engineering admission. Needs help with mechanics and calculus.',
    },
    {
      id: 'j-109',
      area: 'Mohammadpur',
      distanceKm: 2.8,
      level: 'Class 10',
      curriculum: 'English Version',
      subjects: ['Math', 'Physics'],
      pay: 8500, payUnit: 'mo',
      days: '3 days/wk · 1 hr',
      window: 'Afternoons · 4–6pm',
      gender: 'Male',
      posted: '32 min ago',
      match: 88,
      applicants: 6,
      guardian: { name: 'Mrs. Akter', verified: true },
    },
    {
      id: 'j-101',
      area: 'Lalmatia · Block C',
      distanceKm: 0.9,
      level: 'O-Level',
      curriculum: 'Edexcel',
      subjects: ['Physics'],
      pay: 14000, payUnit: 'mo',
      days: '2 days/wk · 2 hr',
      window: 'Weekends',
      gender: 'Any',
      posted: '2 hr ago',
      match: 79,
      applicants: 11,
      guardian: { name: 'Ms. Karim', verified: false },
    },
    {
      id: 'j-097',
      area: 'Dhanmondi 15',
      distanceKm: 1.8,
      level: 'HSC',
      curriculum: 'National',
      subjects: ['Chemistry'],
      pay: 9000, payUnit: 'mo',
      days: '3 days/wk · 1.5 hr',
      window: 'Evenings',
      gender: 'Any',
      posted: '5 hr ago',
      match: 71,
      applicants: 8,
      guardian: { name: 'Mr. Hossain', verified: true },
    },
  ],
  applications: [
    { id: 'a1', jobId: 'j-114', state: 'shortlisted', when: 'today, 9:14am' },
    { id: 'a2', jobId: 'j-109', state: 'location-granted', when: 'yesterday' },
    { id: 'a3', jobId: 'j-101', state: 'applied', when: '2 days ago' },
    { id: 'a4', jobId: 'j-088', state: 'trial-scheduled', when: '3 days ago',
      meta: { area: 'Mirpur DOHS', level: 'Class 9', subjects: ['Math'] } },
    { id: 'a5', jobId: 'j-076', state: 'rejected', when: '1 wk ago',
      meta: { area: 'Mohammadpur', level: 'Class 8', subjects: ['English'] } },
  ],
  classes: [
    { id: 'c1', student: 'Ifrat Rahman', area: 'Dhanmondi 27', subject: 'Physics, Math',
      date: 'Today', time: '6:30pm', dur: '90 min', state: 'upcoming', payPerClass: 750 },
    { id: 'c2', student: 'Saif Akter', area: 'Mohammadpur', subject: 'Math',
      date: 'Today', time: '8:30pm', dur: '60 min', state: 'upcoming', payPerClass: 500 },
    { id: 'c3', student: 'Rumana Hossain', area: 'Mirpur DOHS', subject: 'Higher Math',
      date: 'Tomorrow', time: '4:00pm', dur: '90 min', state: 'upcoming', payPerClass: 800 },
  ],
  chats: [
    { id: 'm1', name: 'Mr. Rahman', preview: 'Approved your location request — see you tomorrow.',
      time: '9:14am', unread: 2, masked: true, last: 'them' },
    { id: 'm2', name: 'Saif Akter', preview: 'Can we move tonight to 9pm?',
      time: '8:02am', unread: 1, masked: true, last: 'them' },
    { id: 'm3', name: 'Tution Media · Support', preview: 'Your NID verification is complete.',
      time: 'Yesterday', unread: 0, masked: false, last: 'them', system: true },
    { id: 'm4', name: 'Rumana Hossain', preview: 'You: Sent the practice set.',
      time: 'Mon', unread: 0, masked: true, last: 'me' },
    { id: 'm5', name: 'Mrs. Akter', preview: 'Thanks, see you Sunday.',
      time: 'Sun', unread: 0, masked: true, last: 'them' },
  ],
  // demand heatmap zones (rough relative to a 320×420 canvas)
  heatmap: [
    { name: 'Dhanmondi 27', x: 0.42, y: 0.34, intensity: 1.0, requests: 18, top: 'Physics · HSC' },
    { name: 'Dhanmondi 15', x: 0.48, y: 0.48, intensity: 0.82, requests: 14, top: 'Math · Class 10' },
    { name: 'Lalmatia',     x: 0.32, y: 0.30, intensity: 0.71, requests: 11, top: 'Edexcel Phys' },
    { name: 'Mohammadpur',  x: 0.22, y: 0.46, intensity: 0.65, requests: 9, top: 'Math · Class 9' },
    { name: 'Kalabagan',    x: 0.58, y: 0.40, intensity: 0.55, requests: 7, top: 'Chemistry' },
    { name: 'Rayer Bazar',  x: 0.18, y: 0.62, intensity: 0.42, requests: 5, top: 'English' },
    { name: 'Hazaribagh',   x: 0.28, y: 0.74, intensity: 0.28, requests: 3, top: 'ICT' },
    { name: 'Shyamoli',     x: 0.16, y: 0.32, intensity: 0.36, requests: 4, top: 'Bangla' },
  ],
};

Object.assign(window, { TM_DATA });
